/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculator.Gradle;

import org.junit.jupiter.api.Test;

import javax.sound.midi.SysexMessage;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    Calculation calculation;
    @Test
    public void testAppHasAGreeting() {
//        App classUnderTest = new App();
        System.out.println("Test1");
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testAdditionOperation() {
        calculation = new Addition();
        double res = calculation.operation(1,2);
        System.out.println("Test2");
        assertEquals(res, 3 );
    }

    @Test
    public void testMultiplication() {
        calculation = new Multiplication();
        double res = calculation.operation(1,2);
        assertEquals(res, 3);
    }
}
