/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculator.Gradle;

public class App {
//    public String getGreeting() {
//        return "Hello world.";
//    }

    public static void main(String[] args) {

    }
}
